@startuml classe
class "Application"{
    -clipboard : String
    -editeur : Editeur
    -fenetre : Fenetre

    +Application() <<constructor>>

    +getClipboard() : String
    +getEditeur() : Editeur
    +getFenetre() : Fenetre
    +setClipboard(clipboard : String) : void

    +deplaceCurseur(direction : char) : void
    +deplaceSelection(direction : char) : void
    +ecrit(c : char) : void
    +supprime() : void
    +copie() : void
    +coupe() : void
    +colle() : void

    +run() : void
}

class "Fenetre"{
    -application : Application
    -textArea : JTextArea
    -highlighter : Highlighter
    -selectionPainter : HighlightPainter
    -cursorPainter : HighlightPainter
    -selectionTag : Object
    -cursorTag : Object
    -actionneur : Actionneur

    +Fenetre(application : Application) <<constructor>>
    
    +getApplication() : Application
    +getTextArea() : JTextArea
    +getHighlighter() : Highlighter
    +getSelectionPainter() : HighlightPainter
    +getCursorPainter() : HighlightPainter
    +getSelectionTag() : Object
    +getCursorTag() : Object
    +getActionneur() : Actionneur
    +setActionneur(actionneur : Actionneur) : void

    +refreshText() : void
    +refreshSelectionHighlight() : void
    +refreshCursorHighlight() : void
    +show() : void
    -initTextArea() : void
}

abstract class "Actionneur"{
    #fenetre : Fenetre

    +Actionneur(fenetre : Fenetre) <<constructor>>

    +getFenetre() : Fenetre

    #changeActionneur(actionneur : Actionneur) : void
}

class "InputActionneur"{
    +InputActionneur(fenetre : Fenetre) <<constructor>>

    +keyPressed(e : KeyEvent) : void
    +keyTyped(e : KeyEvent) : void
    -isPrintableChar(c : char) : boolean
}

class "CommandeActionneur"{
    +CommandeActionneur(fenetre : Fenetre) <<constructor>>

    +keyPressed(e : KeyEvent) : void
    +keyReleased(e : KeyEvent) : void
}

class "Editeur"{
    -texte : StringBuffer
    -curseur : int
    -selection : Selection

    +Editeur() <<constructor>>
    
    +getTexte() : StringBuffer
    +getCurseur() : int
    +getSelection() : Selection

    +writeChar(c : char) : void
    +deleteChar(direction : char) : void
    +moveCurseur(direction : char) : void
    +moveSelection(direction : char) : void
    +resetSelection() : void
    +emptySelection() : boolean
    +getSelectedText() : String
    +setSelectedText(String replacement) : void
    +removeSelectedText() : void
}

class "Selection"{
    -offset : int

    +Selection() <<constructor>>

    +getOffset() : int
    +setOffset(offset : int) : void
}

abstract class "Commande"{
    #application : Application
    #editeur : Editeur

    +Commande(application : Application, editeur : Editeur) <<constructor>>
    
    +getApplication() : Application
    +getEditeur() : Editeur
    
    {abstract}+execute() : void
}

class "Copier"{
    +Copier(application : Application, editeur : Editeur) <<constructor>>
    
    +execute() : void
}

class "Coller"{
    +Coller(application : Application, editeur : Editeur) <<constructor>>
    
    +execute() : void
}

class "Couper"{
    +Couper(application : Application, editeur : Editeur) <<constructor>>
    
    +execute() : void
}

class "DeplacerCurseur"{
    -direction : char
    
    +DeplacerCurseur(application : Application, editeur : Editeur, direction : char) <<constructor>>
    
    +getDirection() : char

    +execute() : void
}

class "DeplacerSelection"{
    -direction : char

    +DeplacerSelection(application : Application, editeur : Editeur, direction : char) <<constructor>>
    
    +getDirection() : char

    +execute() : void
}

class "Ecrire"{
    -c : char
    
    +Ecrire(application : Application, editeur : Editeur, c : char) <<constructor>>
    
    +getChar() : char
    
    +execute() : void
}

class "Supprimer"{
    -direction : char

    +Supprimer(application : Application, editeur : Editeur, direction : char) <<constructor>>
    
    +getDirection() : char
    
    +execute() : void
}

Application *-->"1" Editeur
Application *-->"1" Fenetre
Application -->"0..n" Commande
Fenetre *-->"1" Actionneur
Fenetre "1"<--* Actionneur
Application "1"<-- Commande
Editeur *-->"1" Selection
Commande -->"1" Editeur

Commande <|-- Copier
Commande <|-- Couper
Commande <|-- Coller
Commande <|-- DeplacerCurseur
Commande <|-- DeplacerSelection
Commande <|-- Ecrire
Commande <|-- Supprimer

Actionneur <|-- InputActionneur
Actionneur <|-- CommandeActionneur
@enduml